"""BUILT IN FUNCTIONS"""

# In Python we have lots of built in functions
# built in functions are GLOBALLY available for your use so no need for importing to use these

# common functons include
    # print()
    # len()
    # type()
    # int()
    # float()
    # str()
    # input()
    # list()
    # dict()
    # min()
    # max()
    # sum()
    # sorted()
    # open()
    # file()
    # help()
    # dir()

"""Interesting things i found"""
# If you want to use a reserved keyword as a variable name you put an underscore in front of it.. 
# like "_if = ..."

# You can convert a string into a list of chars by just using list(var)


# exhaustive list of python functions and what they do (what they do explanations generated by AI in additional file because it's too large to include here)

"""VALID VARIABLE NAMING"""
# Python Variable Name Rules
    # A variable name must start with a letter or the underscore character
    # A variable name cannot start with a number
    # A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
    # Variable names are case-sensitive (firstname, Firstname, FirstName and FIRSTNAME) are different variables)

# firstname
# lastname
# age
# country
# city
# first_name
# last_name
# capital_city
# _if # if we want to use reserved word as a variable
# year_2021
# year2021
# current_year_2021
# birth_year
# num1
# num2

"""INVALID VARIABLE NAMES"""

#first-name
#first@name
#first$name
#num-1
#1num

"""TYPICALLY WHEN CODING IN PYTHON WE USE SNAKE CASE NOT CAMEL CASE"""
# this means varaibles will be lowercase and split by underscrores like 
first_name = 'Asabeneh'
last_name = 'Yetayeh'
country = 'Finland'
city = 'Helsinki'
age = 250
is_married = True
skills = ['HTML', 'CSS', 'JS', 'React', 'Python']
person_info = {
   'firstname':'Asabeneh',
   'lastname':'Yetayeh',
   'country':'Finland',
   'city':'Helsinki'
   }